=head1 NAME

Atelier - Lightweight web application framework.

=head1 SYNOPSIS

  # app.psgi
  use Atelier;
  use Plack::Builder;

  builder {
      Atelier->create_app(
          app => 'YourApp', # pass your app namespace
      );
  };

  # YourApp::Dispatcher
  use parent qw/Atelier::Dispatcher::CamelCase/;

  1;

  # YourApp::Pages
  use parent qw/Atelier::Pages/;

  use Plack::Request;
  sub create_request{ Plack::Request->new(shift->env) };

  1;

  # YourApp::Pages::Root
  use parent qw/YourApp::Pages/;

  sub dispatch_index { # "/" or "/index" path route to this dispatch.
      my $self = shift;

      [
         200,
         [ 'Cotent-Type' => 'text/plain' ],
         [ 'Hello,world!' ],
      ];    
  }

=head1 DESCRIPTION

Atelier is lightweight web application framework.
This WAF is very pluggable and useful.

=head2 Sledge like interface.

Atelier is Sledge like interface.

=head1 AUTHOR

Kenta Sato E<lt>karupa@cpan.orgE<gt>

=head1 SEE ALSO

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


=cut

