=head1 NAME

Atelier - Lightweight web application framework.

=head1 SYNOPSIS

  # app.psgi
  use Atelier;
  use Plack::Builder;

  builder {
      Atelier->create_app(
          app => 'YourApp', # pass your app namespace
      );
  };

  # 

=head1 DESCRIPTION

Atelier is lightweight web application framework.


=head1 AUTHOR

Kenta Sato E<lt>karupa@cpan.orgE<gt>

=head1 SEE ALSO

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


=cut

