=head1 NAME

Atelier - Lightweight web application framework.

=head1 SYNOPSIS

  # app.psgi
  use Atelier;
  use Plack::Builder;

  builder {
      Atelier->create_app(
          app => 'YourApp', # pass your app namespace
      );
  };

  # YourApp::Pages
  use parent qw/Atelier::Pages/;
  use Atelier::Plugin::Trigger;
  use Atelier::Plugin::Tiffany (
      engine => 'Text::Xslate',
      option => +{
          syntax => 'TTerse',
      },
  );

  use Plack::Request;
  __PACKAGE__->add_trigger(
      name => 'BEFORE_DISPATCH',
      cb   => sub {
          my $self = shift;
          $self->req( Plack::Request->new($self->env) );
      },
  );

  # YourApp::Pages::Hoge
  use parent qw/YourApp::Pages/;

  sub dispatch_hoge {
      my $self = shift;

      $self->stash->{hoge} = 'hoge';
  }

  # YourApp::Dispatcher
  use parent qw/Atelier::Dispatcher/; # comming soon

  # comming soon

=head1 DESCRIPTION

Atelier is lightweight web application framework.
This WAF is very pluggable and useful.

=head2 Sledge like interface.

Atelier is Sledge like interface.

=head1 AUTHOR

Kenta Sato E<lt>karupa@cpan.orgE<gt>

=head1 SEE ALSO

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


=cut

